language: cpp

sudo: required

compiler:
  - clang

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
branches:
  only:
  - master

before_install:
    - eval "${MATRIX_EVAL}"

script:
  # Link gcc-6 and g++-6 to their standard commands
  #- ln -s /usr/bin/clang-5 /usr/local/bin/clang
  #- ln -s /usr/bin/clang++-5 /usr/local/bin/clang++
  # Export CC and CXX to tell cmake which compiler to use
  #- export CC=/usr/bin/clang-6
  #- export CXX=/usr/bin/clang++-6
  # Check versions of gcc, g++ and cmake
  - $CC -v && g++ -v && cmake --version
  # Run your build commands next
  - $CXX -std=c++1z core/ppmc.cpp -o a.out
  


